name = "my-app"
compatibility_date = "2024-07-20"

# [vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiM2EyNTkyNWYtOGQzYy00ZjBhLTljMjktYTE2ZDBiMWQ5ZWUyIiwidGVuYW50X2lkIjoiZDNlNDdhZGRjZWExYWE0N2U4MDAzNDgxYjFkNzU5MTFmOGNhMzc2MWM0YmMzZWUzNmNhZmQxZTViNjU1YmU5MiIsImludGVybmFsX3NlY3JldCI6Ijg2OThiMTBkLTAxMWQtNGZmMi1hYWRkLTIwMjhkZWQxYzI5YSJ9.wyYtQaM3DUYTXIlGNlk6dF-VH0iECouobZZj92b97m0"

CLOUD_NAME = "dv9ijnrfs"
CLOUD_API_KEY = "755861456191891"
CLOUD_SECRET_KEY = "kUjEM1rrQuwLlYdKT9KkUiH05DI"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"